# Package holding extra entities and automations to be used by Home Assistant for 
# Jacuzzi - Temperature monitor

jacuzzi_package:

  # Create jacuzzi sensors
  # Entities comes from an ESPHome programmed unit using the native Home Assistant API through the ESPHome integration
  sensor:

    # Get jacuzzi temperture min and max values last 3 hrs from statistics
    - platform: statistics
      name: jacuzzi_temperature_min
      entity_id: sensor.jacuzzi_temperature
      state_characteristic: value_min
      precision: 1 
      sampling_size: 10
      max_age:
        hours: 3

    - platform: statistics
      name: jacuzzi_temperature_max
      entity_id: sensor.jacuzzi_temperature
      state_characteristic: value_max
      precision: 1 
      sampling_size: 10
      max_age:
        hours: 3   

    # Get Jacuzzi temperature change rate
    - platform: derivative
      source: sensor.jacuzzi_temperature
      name: Jacuzzi temperature change per hour
      round: 1
      unit_time: h 
      time_window: "01:00:00"

  # Create jacuzzi automations
  automation:

    # Jacuzzi low temperatue
    - alias: "Jacuzzi temperature too low"
      trigger:
        platform: numeric_state
        entity_id: sensor.jacuzzi_temperature
        below: 32
      action:
        service: notify.mobile_app_arve_sin_iphone
        data_template:
          title: Temperatur i jacuzzi er lav 
          message: "Temperaturen er nå {{ states('sensor.jacuzzi_temperature') }} ºC" 
    # Jacuzzi temperature back to normal"
    - alias: "Jacuzzi temperature OK"
      trigger:
        platform: numeric_state
        entity_id: sensor.jacuzzi_temperature
        above: 32
      action:
        service: notify.mobile_app_arve_sin_iphone
        data_template:
          title: Temperatur i jacuzzi er OK
          message: "Temperaturen er nå {{ states('sensor.jacuzzi_temperature') }} ºC"      

    # No change in temperatur from jacuzzi
    - alias: "Jacuzzi no temperature data received"
      trigger:
        - platform: template
          value_template: "{{ states('sensor.jacuzzi_temperature_max') == states('sensor.jacuzzi_temperature_min') }}"
      action:
        service: notify.mobile_app_arve_sin_iphone
        data_template:
          title: Jacuzzi  
          message: "Ingen data mottatt!"   