sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_voltage
    name: ${friendly_name} PV voltage
    address: 0x3100
    unit_of_measurement: "V"
    device_class: voltage
    icon: mdi:alpha-v-circle-outline
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_current
    name: ${friendly_name} PV current
    address: 0x3101
    unit_of_measurement: "A"
    device_class: current
    icon: mdi:current-dc
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_power
    name: ${friendly_name} PV power
    address: 0x3102
    unit_of_measurement: "W"
    device_class: power
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_voltage
    name: ${friendly_name} charging voltage
    address: 0x3104
    unit_of_measurement: "V"
    device_class: voltage
    icon: mdi:alpha-v-circle-outline
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_current
    name: ${friendly_name} charging current
    address: 0x3105
    unit_of_measurement: "A"
    device_class: current
    icon: mdi:current-dc
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_power
    name: ${friendly_name} charging power
    address: 0x3106
    unit_of_measurement: "W"
    device_class: power
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: load_voltage
    name: ${friendly_name} load voltage
    address: 0x310C
    unit_of_measurement: "V"
    device_class: voltage
    icon: mdi:alpha-v-circle-outline
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: load_current
    name: ${friendly_name} load Current
    address: 0x310D
    unit_of_measurement: "A"
    device_class: current
    icon: mdi:current-dc
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: load_power
    name: ${friendly_name} load power
    address: 0x310E
    unit_of_measurement: "W"
    device_class: power
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_temperature
    name: ${friendly_name} battery temperature
    address: 0x3110
    unit_of_measurement: °C
    device_class: temperature
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: device_temperature
    name: ${friendly_name} device temperature
    address: 0x3111
    unit_of_measurement: °C
    device_class: temperature
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  # - platform: modbus_controller
  #   modbus_controller_id: epever
  #   id: power_components_temperature
  #   name: ${friendly_name} power components temperature
  #   address: 0x3112
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   register_type: read
  #   value_type: S_WORD
  #   accuracy_decimals: 1
  #   filters:
  #     - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_soc
    name: ${friendly_name} battery SOC # State Of Charge
    address: 0x311A
    unit_of_measurement: "%"
    device_class: battery
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_status
    name: ${friendly_name} battery status
    address: 0x3200
    register_type: read
    value_type: U_WORD
    bitmask: 0x7  #(Bits 0-3)
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_mode
    name: ${friendly_name} charging mode
    address: 0x3201
    register_type: read
    value_type: U_WORD
    bitmask: 0x6  #(Bits 3-2)
    accuracy_decimals: 0
