sensor:
  
  # - platform: modbus_controller
  #   modbus_controller_id: epever
  #   id: battery_capacity
  #   address: 0x9001
  #   name: ${prefix} battery capacity
  #   unit_of_measurement: "Ah"
  #   device_class: energy
  #   register_type: holding
  #   value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_limit_voltage
    address: 0x9004
    name: ${prefix} charging limit voltage
    unit_of_measurement: "V"
    device_class: voltage
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: boost_voltage
    address: 0x9007
    name: ${prefix} boost voltage
    unit_of_measurement: "V"
    device_class: voltage
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: float_voltage
    address: 0x9008
    name: ${prefix} float voltage
    unit_of_measurement: "V"
    device_class: voltage
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: low_voltage_disconnect
    address: 0x900D
    name: ${prefix} low voltage disconnect
    unit_of_measurement: "V"
    device_class: voltage
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

