esphome:
  name: jacuzzi
  platform: ESP8266
  board: esp01_1m

time:
  - platform: sntp
    timezone: Europe/Oslo

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 10s
  manual_ip:
    static_ip: !secret jacuzzi_ip
    gateway: !secret gateway
    subnet: !secret subnet  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jacuzzi Fallback Hotspot"
    password: "DpTaMuhtEvdK"

captive_portal:

# Enable logging
logger:

# Home Assistant API (Does not work well with deep_sleep. Using mqtt instead))
# api:
#   password: !secret ota_password

# Enable OTA
ota:
  password: !secret ota_password
  
# Dallas 1-wire
dallas:
  - pin: 2
    update_interval: 10s

# Dallas DS18B20 Temperature sensor
sensor:
  - platform: dallas
    address: 0x7B0317248E50FF28
    name: "Jacuzzi Temperature"
    retain: true
    filters:
    - max:

# Enable deep sleep
deep_sleep:
  run_duration: 10s
  sleep_duration: 15min
  id: deep_sleep_1
  
# Setup mqtt
mqtt:
  broker: !secret mqtt_broker
  discovery: true
  discovery_retain: true
  discovery_prefix: !secret mqtt_discovery_prefix
  birth_message:
  will_message:
  on_message:
    - topic: jacuzzi/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: jacuzzi/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1  
