- platform: sensibo
  api_key: !secret sensibo_api_key

- platform: generic_thermostat
  unique_id: !secret uuid_generic_thermostat_spisestue
  name: Spisestue
  heater: switch.spisestue_turned_on
  target_sensor: sensor.spisestue_temperature
  target_temp: 23
  min_temp: 10
  max_temp: 30 
  precision: 1

- platform: generic_thermostat
  unique_id: !secret uuid_generic_thermostat_kontor
  name: Kontor
  heater: switch.kontor_turned_on
  target_sensor: sensor.netatmo_ws1_stue_kontor_temperature
  target_temp: 23
  min_temp: 10
  max_temp: 30
  precision: 1

