# Temp setback night switch (on/off set by user)
temp_setback_night_switch:
  name: Temp setback night switch
  icon: mdi:weather-night
  initial: off

# Temp setback night state (state holder)  
temp_setback_night_state:
  name: Temp setback night state
  icon: mdi:weather-night
  initial: off


# Temp setback door open switch (on/off set by user)
temp_setback_door_open_switch:
  name: Temp setback door open switch
  icon: mdi:door-open
  initial: on

# Temp setback door open state (state holder)
temp_setback_door_open_state:  
  name: Temp setback door open state
  icon: mdi:door-open
  initial: off
