# Slider to set night setback temperatur
slider_temp_setback_night:
  name: Temperature night setback temp
  initial: 2
  min: 1
  max: 5
  step: 1
  mode: slider
  unit_of_measurement: "ºC"

# Slider to set door open setback temperatur
slider_temp_setback_door_open:
  name: Temperature door open setback temp
  initial: 8
  min: 1
  max: 10
  step: 1
  mode: slider
  unit_of_measurement: "ºC"
