- id: '1667350797969'
  alias: Freezer temperature OK
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.fryser_temperature
    below: -18
  condition: []
  action:
  - service: notify.mobile_app_arve_sin_iphone
    data_template:
      title: Temperatur i fryser er OK
      message: Temperaturen er nå {{ states('sensor.fryser_temperature') }} ºC
  mode: single
- id: '1667350881512'
  alias: Freezer temperature OK
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.fryser_temperature
    below: -18
  condition: []
  action:
  - service: notify.mobile_app_arve_sin_iphone
    data_template:
      title: Temperatur i fryser er OK
      message: Temperaturen er nå {{ states('sensor.fryser_temperature') }} ºC
  mode: single
