homeassistant:
  
  # Name of the location where Home Assistant is running
  name: Hjemme
  
  # External and internal url for Home Assistant
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ha_elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

  # Currency
  currency: NOK

  # Country
  country: "NO"
  
  # customization
  customize: !include customize/customize.yaml
  customize_glob: !include customize/customize_glob.yaml

  # Allow external dirs
  allowlist_external_dirs:
    - /config/file_dump
  
  # Allow external urls
  # allowlist_external_urls:
  #   - "http://images.com/image1.png"  

  # Packages
  packages: !include_dir_merge_named packages/
  
# Energy dashboard
energy:

# http config (for reverse proxy)
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.1     # IP address of the gateway of the docker iot-net network.

# Enables the frontend
frontend: 
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Enables configuration UI
config:
#  !include config_files/http.yaml

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Homa assitant database storage
recorder:
  purge_keep_days: 7  

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enable backup
backup:

# Logger setup
logger: 
  default: info
  logs:
    homeassistant.components.http.ban: warning

# Scenes
scene: !include scenes.yaml  

# Lights
light: !include lights.yaml

# Mobile
mobile_app:
ios:

# Speedtest (Does not work well in a docker container)
# speedtestdotnet:

# Utility Meter
utility_meter: !include_dir_merge_list utility_meter/

# Automation
automation: !include_dir_merge_list automation/
