homeassistant:
  
  # Name of the location where Home Assistant is running
  name: Hjemme
  
  # External and internal url for Home Assistant
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url

  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ha_elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

  # Currency
  currency: NOK
  
  # customization
  customize: !include customize/customize.yaml
  customize_glob: !include customize/customize_glob.yaml

  # Allow external dirs
  allowlist_external_dirs:
    - /config/file_dump
  
  # Allow external urls
  # allowlist_external_urls:
  #   - "http://images.com/image1.png"  

# http config (for reverse proxy)
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.1     # IP address of the gateway of the docker iot-net network.

# Enables the frontend
#frontend: !include config_files/frontend.yaml
frontend: 
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Enables configuration UI
config:
#  !include config_files/http.yaml

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Homa assitant database storage
recorder:
  purge_keep_days: 7  

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Logger stup
logger: !include config_files/logger.yaml

# Track the sun
sun:

# System Helth monitoring
system_health:

# Scenes
scene: !include scenes.yaml  

# Lights
light: !include lights.yaml

# Scripts
# script: !include scripts.yaml

# Groups
group: !include groups.yaml

# Mobile
mobile_app:
ios:

# Speedtest (Does not work well in a docker container)
# speedtestdotnet:

# Google 
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# Config
input_boolean: !include config_files/input_boolean.yaml
input_number: !include config_files/input_number.yaml
input_datetime: !include config_files/input_datetime.yaml
input_select: !include config_files/input_select.yaml
netatmo: !include config_files/netatmo.yaml  
verisure: !include config_files/verisure.yaml
air_quality: !include config_files/air_quality.yaml
mqtt: !include config_files/mqtt.yaml
tradfri: !include config_files/tradfri.yaml
climate: !include config_files/climate.yaml
duckdns: !include config_files/duckdns.yaml

# Sensor
sensor: !include_dir_merge_list sensor/sensor/
binary_sensor: !include_dir_merge_list sensor/binary_sensor/

# Switch
switch: !include_dir_merge_list switch/

# Automation
automation: !include_dir_merge_list automation/
