# Temp setback at door open 
- alias: "Temperature setback at door open for 5 minutes"
  trigger:
    platform: state
    entity_id: group.exterior_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.temp_setback_door_open_state
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.temp_setback_door_open_state
    - service: climate.set_temperature
      data_template:
        entity_id: climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int - states('input_number.slider_temp_setback_door_open') | int }}"
    - service: climate.turn_off
      entity_id: group.climate_open_door_affected

# Temp setback restore at door closed
- alias: "Temperature setback restore at door closed"
  trigger:
    platform: state
    entity_id: group.exterior_doors
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: group.exterior_doors 
      state: 'off' 
    - condition: state
      entity_id: input_boolean.temp_setback_door_open_state
      state: 'on'              
  action:
    - service: input_boolean.turn_off 
      entity_id: input_boolean.temp_setback_door_open_state
    - service: climate.set_temperature
      data_template:
        entity_id: climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int + states('input_number.slider_temp_setback_door_open') | int }}"
    - service: climate.turn_on
      entity_id: group.climate_open_door_affected


# Temp setback at night - start
- alias: "Temperature setback night start"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time')[0:5] == states('input_datetime.temp_setback_night_start_time')[0:5] }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.temp_setback_night_switch
        state: 'on'
      - condition: state
        entity_id: input_boolean.temp_setback_night_state
        state: 'off'
      - condition: time
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: input_boolean.turn_on 
      entity_id: input_boolean.temp_setback_night_state
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int - states('input_number.slider_temp_setback_night') | int }}"
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.spisestue
        temperature: "{{ states('sensor.mill_spisestue_setpoint_temp') | int - states('input_number.slider_temp_setback_night') | int }}"
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.stue
        temperature: "{{ states('sensor.mill_stue_setpoint_temp') | int - states('input_number.slider_temp_setback_night') | int }}"  
        
# Temp setback at night - end
- alias: "Temperature setback night end"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time')[0:5] == states('input_datetime.temp_setback_night_end_time')[0:5] }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.temp_setback_night_state
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    - service: input_boolean.turn_off 
      entity_id: input_boolean.temp_setback_night_state
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int + states('input_number.slider_temp_setback_night') | int }}"
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.spisestue
        temperature: "{{ states('sensor.mill_spisestue_setpoint_temp') | int + states('input_number.slider_temp_setback_night') | int }}"
    - service: climate.set_temperature
      data_template:
        entity_id:
          - climate.stue
        temperature: "{{ states('sensor.mill_stue_setpoint_temp') | int + states('input_number.slider_temp_setback_night') | int }}"  
