- alias: Update OpenUV every 30 minutes while the sun is at least 10 degrees above the horizon
  trigger:
    platform: time_pattern
    minutes: '/30'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 10
  action:
    service: openuv.update_uv_index_data
    