# Door open 
- alias: "Temperature setback at door open for 5 minutes"
  trigger:
    platform: state
    entity_id: group.exterior_doors
    from: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.temp_setback_door_open_state
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.temp_setback_door_open_state
    - service: climate.set_temperature
      data_template:
        entity_id: climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int - states('input_number.slider_temp_setback_door_open') | int }}"
    - service: climate.turn_off
      entity_id: group.climate_open_door_affected

# Door closed
- alias: "Temperature setback restore at door closed"
  trigger:
    platform: state
    entity_id: group.exterior_doors
    from: 'on'
  condition:
    - condition: state
      entity_id: group.exterior_doors 
      state: 'off' 
    - condition: state
      entity_id: input_boolean.temp_setback_door_open_state
      state: 'on'              
  action:
    - service: input_boolean.turn_off 
      entity_id: input_boolean.temp_setback_door_open_state
    - service: climate.set_temperature
      data_template:
        entity_id: climate.varmepumpe
        temperature: "{{ states('sensor.sensibo_setpoint_temp') | int + states('input_number.slider_temp_setback_door_open') | int }}"
    - service: climate.turn_on
      entity_id: group.climate_open_door_affected
        