# Get stue temperature min and max values from statistics
- platform: statistics
  name: netatmo_ws1_stue_temperature_min
  entity_id: sensor.netatmo_ws1_stue_temperature
  state_characteristic: value_min
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24

- platform: statistics
  name: netatmo_ws1_stue_temperature_max
  entity_id: sensor.netatmo_ws1_stue_temperature
  state_characteristic: value_max
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24    

# Get ute temperature min and max values from statistics
- platform: statistics
  name: netatmo_ws1_stue_ute_temperature_min
  entity_id: sensor.netatmo_ws1_stue_ute_temperature
  state_characteristic: value_min
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24

- platform: statistics
  name: netatmo_ws1_stue_ute_temperature_max
  entity_id: sensor.netatmo_ws1_stue_ute_temperature
  state_characteristic: value_max
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24    

# Get kontor temperature min and max values from statistics
- platform: statistics
  name: netatmo_ws1_stue_kontor_temperature_min
  entity_id: sensor.netatmo_ws1_stue_kontor_temperature
  state_characteristic: value_min
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24

- platform: statistics
  name: netatmo_ws1_stue_kontor_temperature_max
  entity_id: sensor.netatmo_ws1_stue_kontor_temperature
  state_characteristic: value_max
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24    

- platform: template
  sensors:
    # Get formatted pressure
    netatmo_ws1_stue_pressure_f:
      friendly_name: "Trykk"
      unit_of_measurement: "hPa"
      value_template: "{{ '{0:.0f}'.format(states('sensor.netatmo_ws1_stue_pressure')|float) }}"
      icon_template: mdi:gauge

# Get Netatmo ute temperature change rate
- platform: derivative
  source: sensor.netatmo_ws1_stue_ute_temperature
  name: Netatmo ute temp change per hour
  round: 1
  unit_time: h 
  time_window: "01:00:00"
