# Get stue temperature statisics
- platform: statistics
  name: netatmo_ws1_stue_temperature_stats
  entity_id: sensor.netatmo_ws1_stue_temperature
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24

# Get ute temperature statisics
- platform: statistics
  name: netatmo_ws1_stue_ute_temperature_stats
  entity_id: sensor.netatmo_ws1_stue_ute_temperature
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24

# Get sov1 temperature statisics
- platform: statistics
  name: netatmo_ws1_stue_sov1_temperature_stats
  entity_id: sensor.netatmo_ws1_stue_sov1_temperature
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24   

# Get kontor temperature statisics
- platform: statistics
  name: netatmo_ws1_stue_kontor_temperature_stats
  entity_id: sensor.netatmo_ws1_stue_kontor_temperature
  precision: 1 
  sampling_size: 120
  max_age:
    hours: 24    

- platform: template
  sensors:
    # Get stue tempersture min and max values from statistics
    netatmo_ws1_stue_temperature_min:
      friendly_name: Temp stue min
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_temperature_stats', 'min_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: "ºC" 
    netatmo_ws1_stue_temperature_max:
      friendly_name: Temp stue max
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_temperature_stats', 'max_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: "ºC"      
    # Get sov1 tempersture min and max values from statistics
    netatmo_ws1_stue_sov1_temperature_min:
      friendly_name: Temp sov1 min
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_sov1_temperature_stats', 'min_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: "ºC" 
    netatmo_ws1_stue_sov1_temperature_max:
      friendly_name: Temp sov1 max
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_sov1_temperature_stats', 'max_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: "ºC"      
    # Get ute tempersture min and max values from statistics
    netatmo_ws1_stue_ute_temperature_min:
      friendly_name: Temp ute min
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_ute_temperature_stats', 'min_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: "ºC" 
    netatmo_ws1_stue_ute_temperature_max:
      friendly_name: Temp ute max
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_ute_temperature_stats', 'max_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: "ºC"      
    # Get kontor tempersture min and max values from statistics
    netatmo_ws1_stue_kontor_temperature_min:
      friendly_name: Temp kontor min
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_kontor_temperature_stats', 'min_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: "ºC" 
    netatmo_ws1_stue_kontor_temperature_max:
      friendly_name: Temp kontor max
      value_template: "{{ state_attr('sensor.netatmo_ws1_stue_kontor_temperature_stats', 'max_value')|round(1) }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: "ºC"      
    # Get formatted pressure
    netatmo_ws1_stue_pressure_f:
      friendly_name: "Trykk"
      unit_of_measurement: "hPa"
      value_template: "{{ '{0:.0f}'.format(states('sensor.netatmo_ws1_stue_pressure')|float) }}"
      icon_template: mdi:gauge

# Get Netatmo ute temperature change rate
- platform: derivative
  source: sensor.netatmo_ws1_stue_ute_temperature
  name: Netatmo ute temp change per hour
  round: 1
  unit_time: h 
  time_window: "01:00:00"
