- platform: template
  sensors:
    current_uv_index_f:
      friendly_name: "UV-index"
      value_template: "{{ '{0:.1f}'.format(states('sensor.current_uv_index')|float) }}"
      icon_template: mdi:weather-sunny
    max_uv_index_f:
      friendly_name: "UV-index"
      value_template: "{{ '{0:.1f}'.format(states('sensor.max_uv_index')|float) }}"
      icon_template: mdi:weather-sunny
    current_ozone_level_f:
      friendly_name: "Ozon-nivå"
      value_template: "{{ '{0:.1f}'.format(states('sensor.current_ozone_level')|float) }}"
      icon_template: mdi:weather-sunny
    current_uv_level_f: 
      friendly_name: "UV-nivå" 
      value_template: >
        {% set i = states('sensor.current_uv_level') %}
        {% if i == 'Low' %}
          Lav
        {% elif i == 'Moderate' %}
          Moderat
        {% elif i == 'High' %}
          Høy
        {% elif i == 'Very High' %}
          Veldig høy
        {% elif i == 'Extreme' %}
          Ekstrem høy
        {% else %}
          Ukjent
        {% endif %}
      icon_template: mdi:weather-sunny  

