# pollenvarsel.no REST API
#
# This is how to find the correct Url:
# 1. Open Chrome and go to https://pollenkontroll.no/pollenvarsel
# 2. Press F12 and select "Network"
# 3. In the web-site, select the area. (eg. Trøndelag)
# 4. Find the Request URL that is retrieved and which consists of some numbers and letters
#    (eg. https://pollenkontroll.no/api/middleware/pollen/f2911165-bc25-494d-a331-42c05e14cfe2)
# 5. Remove "? T = xxxxxx" in the URL and use that address as resource in the rest platform

# Today's Pollen Index
- platform: rest
  name: 'Pollen values today'
  json_attributes_path: "$.forecast[0]"
  json_attributes:
    - allergens
  resource: !secret pollen_url
  value_template: "{{ value_json.forecast[0].date }}"   
  scan_interval: 21600 # 6hrs

- platform: template
  sensors:
    
    pollen_num_1:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[0]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[0]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_1:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[0]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[0]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy

    pollen_num_2:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[1]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[1]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_2:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[1]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[1]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
  
    pollen_num_3:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[2]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[2]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_3:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[2]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[2]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
  
    pollen_num_4:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[3]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[3]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_4:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[3]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[3]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
        
    pollen_num_5:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[4]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[4]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_5:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[4]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[4]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
      
    pollen_num_6:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[5]["name"]}}
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[5]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_desc_6:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_today", "allergens")[5]["name"]}} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_today', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_today", "allergens")[5]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy


# Tomorrows's Pollen Index
- platform: rest
  name: 'Pollen values tomorrow'
  json_attributes_path: "$.forecast[1]"
  json_attributes:
    - allergens
  resource: !secret pollen_url
  value_template: "{{ value_json.forecast[1].date }}"   
  scan_interval: 21600 # 6hrs

- platform: template
  sensors:

    pollen_tm_num_1:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[0]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[0]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_1:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[0]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[0]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy

    pollen_tm_num_2:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[1]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[1]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_2:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[1]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[1]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
  
    pollen_tm_num_3:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[2]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[2]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_3:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[2]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[2]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
  
    pollen_tm_num_4:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[3]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[3]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_4:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[3]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[3]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
        
    pollen_tm_num_5:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[4]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[4]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_5:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[4]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[4]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
      
    pollen_tm_num_6:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[5]["name"] }}
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          0
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[5]["level_number"] }}
        {% endif %}
      icon_template: mdi:allergy
    pollen_tm_desc_6:
      friendly_name_template: >
        {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[5]["name"] }} beskrivelse
      value_template: >
        {% if is_state('sensor.pollen_values_tomorrow', 'unknown') %}
          Ukjent
        {% else %}
          {{ state_attr("sensor.pollen_values_tomorrow", "allergens")[5]["level_description"] }}
        {% endif %}
      icon_template: mdi:allergy
  