# Get real speedtest data from json-file produced by scheduled execution of speedtest cli at 
# regular intervals outside the docker container. The folder must be on a shared docker volume
# and defined in the "allowlist_external_dirs:"-section in configuration.yaml
# Please note that the file platform only reads the last line of the file, so all ending CRLF must be removed.

- platform: file
  name: real_speedtest_download
  file_path: /config/file_dump/speedtest.json
  value_template: "{{ '{0:,.0f}'.format(value_json['download']['bandwidth'] |float / 125000) }}"
  unit_of_measurement: 'Mbps'

- platform: file
  name: real_speedtest_upload
  file_path: /config/file_dump/speedtest.json
  value_template: "{{ '{0:,.0f}'.format(value_json['upload']['bandwidth'] |float / 125000) }}"
  unit_of_measurement: 'Mbps'

- platform: file
  name: real_speedtest_ping
  file_path: /config/file_dump/speedtest.json
  value_template: "{{ value_json['ping']['latency'] | round(1) }}"
  unit_of_measurement: 'ms'

- platform: file
  name: real_speedtest_server_name
  file_path: /config/file_dump/speedtest.json
  value_template: "{{ value_json['server']['name'] }}"

- platform: file
  name: real_speedtest_server_location
  file_path: /config/file_dump/speedtest.json
  value_template: "{{ value_json['server']['location'] }}"

  # Get real speedtest statistics

- platform: statistics
  name: real_speedtest_ping_stats
  entity_id: sensor.real_speedtest_pings
  precision: 2 
  sampling_size: 48
  max_age:
    hours: 24

- platform: statistics
  name: real_speedtest_download_stats
  entity_id: sensor.real_speedtest_download
  precision: 0 
  sampling_size: 48
  max_age:
    hours: 24

- platform: statistics
  name: real_speedtest_upload_stats
  entity_id: sensor.real_speedtest_upload
  precision: 0 
  sampling_size: 48
  max_age:
    hours: 24

# Get real speedtest min and max values from statistics

- platform: template
  sensors:
    
    real_speedtest_ping_min:
      friendly_name: Ping min
      value_template: "{{ state_attr('sensor.real_speedtest_ping_stats', 'min_value') }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: 'ms' 
    real_speedtest_ping_max:
      friendly_name: Ping max
      value_template: "{{ state_attr('sensor.real_speedtest_ping_stats', 'max_value') }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: 'ms'

    real_speedtest_download_min:
      friendly_name: Download min
      value_template: "{{ state_attr('sensor.real_speedtest_download_stats', 'min_value') }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: 'Mbps'  
    real_speedtest_download_max:
      friendly_name: Download max
      value_template: "{{ state_attr('sensor.real_speedtest_download_stats', 'max_value') }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: 'Mbps'
    
    real_speedtest_upload_min:
      friendly_name: Upload min
      value_template: "{{ state_attr('sensor.real_speedtest_upload_stats', 'min_value') }}"
      icon_template: mdi:format-vertical-align-bottom
      unit_of_measurement: 'Mbps'  
    real_speedtest_upload_max:
      friendly_name: Upload max
      value_template: "{{ state_attr('sensor.real_speedtest_upload_stats', 'max_value') }}"
      icon_template: mdi:format-vertical-align-top
      unit_of_measurement: 'Mbps'
