- platform: template
  sensors:
    next_sunrise:
      friendly_name: 'Soloppgang'
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M:%S') }}
      icon_template: mdi:weather-sunset-up
    next_sunset:
      friendly_name: 'Solnedgang'
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M:%S') }}
      icon_template: mdi:weather-sunset-down
