- platform: systemmonitor
  resources:
    - type: load_1m
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: swap_use_percent
    - type: swap_use
    - type: disk_use_percent
      arg: /config
    - type: last_boot
    
- platform: uptime
  name: Time online

- platform: command_line
  name: Version current
  command: "hass --version"
  
- platform: mqtt
  name: MQTT Broker version
  state_topic: "$SYS/broker/version"
  icon: mdi:tray-full

- platform: mqtt
  name: MQTT Broker uptime
  state_topic: "$SYS/broker/uptime"
  value_template: "{{ relative_time( now() - timedelta( seconds = value.rstrip('seconds') | int )) }}"
  icon: mdi:clock

- platform: mqtt
  name: Homey version 
  state_topic: "homey/system/info"
  value_template: "{{ value_json.system.homeyVersion }}" 
  icon: mdi:circle-off-outline

- platform: mqtt
  name: Homey uptime 
  state_topic: "homey/system/info"
  value_template: "{{ relative_time( now() - timedelta( seconds = value_json.system.uptime )) }}"
  icon: mdi:clock  